cookie:
  expiry_days: 30
  key: auth-app-key
  name: auth-app-key
credentials:
  usernames:
    nicole:
      email: nicole@gmail.com
      failed_login_attempts: 0
      first_name: Nicole
      last_name: Lucas
      logged_in: false
      password: $2b$12$OW2XlJ6KvUYzUho173vdReZtiEOoBSSTiImat3IipbSaL5WtR/S6u
      roles:
      - admin
      - viewer
