cookie:
  expiry_days: 30
  key: auth-app-key
  name: auth-app-key
credentials:
  usernames:
    adrianac:
      email: adriana@gmail.com
      first_name: adriana
      last_name: chavez
      logged_in: false
      password: $2b$12$NgWOid.9Sg2XeLAhjEzjbe7jvjjv2cnjCbgE3Q3epDFvrcfz9o7Nq
      roles: null
    nicole:
      email: nicole@gmail.com
      failed_login_attempts: 0
      first_name: Nicole
      last_name: Lucas
      logged_in: false
      password: $2b$12$OW2XlJ6KvUYzUho173vdReZtiEOoBSSTiImat3IipbSaL5WtR/S6u
      roles:
      - admin
      - viewer
